/* Emergence Kernel - Multiboot2 parser */

#include <stdint.h>
#include <stddef.h>
#include "arch/x86_64/multiboot2.h"
#include "kernel/pmm.h"
#include "arch/x86_64/serial.h"
#include "kernel/klog.h"

/* External minilibc function */
extern int snprintf(char *str, size_t size, const char *format, ...);

/* External embedded command line fallback (generated by Makefile) */
extern const char embedded_cmdline[];

/* External function for serial output */
extern void serial_puts(const char *str);
extern void serial_putc(char c);

/* Global kernel command line (max 1024 bytes) */
static char kernel_cmdline[1024];

/* Store multiboot info address and size for PMM reservation */
static uint32_t stored_mbi_addr = 0;
static uint32_t stored_mbi_size = 0;

/* Parse multiboot2 command line tag */
static void parse_cmdline(multiboot_tag_cmdline_t *tag) {
    const char *src = tag->cmdline;
    size_t i = 0;

    /* Copy cmdline string to global buffer, truncate to 1023 bytes */
    while (i < sizeof(kernel_cmdline) - 1 && src[i] != '\0') {
        kernel_cmdline[i] = src[i];
        i++;
    }

    /* Ensure null-termination */
    kernel_cmdline[i] = '\0';
    klog_debug("KERN", "Parsed cmdline from multiboot: %s", kernel_cmdline);
}

/* Simple key-value parser for cmdline */
/* Format: key1=value1 key2=value2 or key1="quoted value" */
const char *cmdline_get_value(const char *key) {
    static char value_buf[256];
    const char *p = kernel_cmdline;
    size_t key_len = 0;

    /* Get key length */
    const char *key_end = key;
    while (*key_end != '\0') {
        key_len++;
        key_end++;
    }

    /* Search for key=value pattern */
    while (*p != '\0') {
        /* Skip leading whitespace */
        while (*p == ' ') p++;

        /* Check if this token starts with our key */
        if (p[0] == '-' && p[1] == '-') {
            p += 2; /* Skip '--' */
        }

        /* Compare key */
        size_t i = 0;
        int match = 1;
        while (i < key_len && p[i] != '\0' && p[i] != '=' && p[i] != ' ') {
            if (p[i] != key[i]) {
                match = 0;
                break;
            }
            i++;
        }

        /* Check for match followed by '=' */
        if (match && p[i] == '=') {
            /* Found it! Copy value */
            p += i + 1; /* Skip key and '=' */

            /* Check if value is quoted */
            int in_quotes = 0;
            if (*p == '"') {
                in_quotes = 1;
                p++; /* Skip opening quote */
            }

            size_t v = 0;
            while (*p != '\0' && v < sizeof(value_buf) - 1) {
                if (in_quotes) {
                    if (*p == '"') {
                        p++; /* Skip closing quote */
                        break;
                    }
                    value_buf[v++] = *p++;
                } else {
                    if (*p == ' ') break;
                    value_buf[v++] = *p++;
                }
            }
            value_buf[v] = '\0';
            return value_buf;
        }

        /* Skip to next token */
        while (*p != '\0' && *p != ' ') p++;
    }

    return NULL;
}

/* Parse multiboot2 memory map tag */
static void parse_memory_map(multiboot_tag_mmap_t *tag) {
    multiboot_mmap_entry_t *entry;
    uint64_t total_pages = 0;
    uint64_t usable_pages = 0;
    int i = 0;

    klog_debug("PMM", "Parsing memory map");

    /* Iterate through memory map entries */
    entry = tag->entries;
    while ((uint8_t *)entry < (uint8_t *)tag + tag->size) {
        uint64_t base = entry->base_addr;
        uint64_t length = entry->length;
        uint32_t type = entry->type;

        if (type == MULTIBOOT_MEMORY_AVAILABLE) {
            /* Align base to page boundary */
            uint64_t aligned_base = (base + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1);
            uint64_t aligned_length = length - (aligned_base - base);

            /* Round down length to page boundary */
            aligned_length = aligned_length & ~(PAGE_SIZE - 1);

            if (aligned_length >= PAGE_SIZE) {
                pmm_add_region(aligned_base, aligned_length);
                usable_pages += aligned_length / PAGE_SIZE;
                klog_debug("PMM", "Added region at %p, size %lX bytes",
                          (void *)aligned_base, aligned_length);
            }
        }

        total_pages += (length + PAGE_SIZE - 1) / PAGE_SIZE;

        /* Move to next entry */
        entry = (multiboot_mmap_entry_t *)((uint8_t *)entry + tag->entry_size);
        i++;
    }

    klog_debug("PMM", "Total memory: %lX bytes", total_pages * PAGE_SIZE);
    klog_debug("PMM", "Usable memory: %lX bytes (%lX pages)",
              usable_pages * PAGE_SIZE, usable_pages);
}

/* Parse multiboot2 information structure */
void multiboot2_parse(uint32_t mbi_addr) {
    multiboot_info_t *mbi = (multiboot_info_t *)(uint64_t)mbi_addr;
    multiboot_tag_t *tag;
    uint64_t total_size;
    int found_memory = 0;

    /* Store MBI info for PMM reservation */
    stored_mbi_addr = mbi_addr;

    klog_debug("PMM", "Parsing multiboot2 info at %p", (void *)(uint64_t)mbi_addr);

    /* Check if multiboot info address is in a reasonable range */
    if (mbi_addr < 0x100000 || mbi_addr > 0x10000000) {
        klog_warn("PMM", "Multiboot info address looks suspicious");
    }

    /* Debug: Print first 32 bytes of multiboot info */
    klog_debug("PMM", "Multiboot info dump:");
    {
        uint8_t *mbi_bytes = (uint8_t *)mbi;
        char dump_buf[128];
        int pos = 0;
        for (int i = 0; i < 32 && pos < 100; i++) {
            pos += snprintf(dump_buf + pos, sizeof(dump_buf) - pos, "%02X ", mbi_bytes[i]);
        }
        klog_debug("PMM", "  %s", dump_buf);
    }

    /* Check if multiboot info is valid */
    if (mbi_addr == 0) {
        klog_debug("PMM", "No multiboot info provided");
        goto use_default_cmdline;
    }

    total_size = mbi->total_size;

    /* Store MBI size for PMM reservation (align to page) */
    stored_mbi_size = (uint32_t)total_size;

    /* If total_size is 0 or too small, boot loader didn't provide info */
    if (total_size < sizeof(multiboot_info_t)) {
        klog_debug("PMM", "Invalid multiboot info (size=%lX), using defaults", total_size);
        goto use_default_cmdline;
    }

    klog_debug("PMM", "Total size: %lX bytes", total_size);

    /* Iterate through tags */
    tag = (multiboot_tag_t *)(mbi + 1);

    while (tag->type != MULTIBOOT_TAG_END) {
        /* Skip padding to 8-byte alignment */
        if (tag->type == 0 && tag->size == 0) {
            break;
        }

        /* Check for valid tag size */
        if (tag->size < 8 || tag->size > 4096) {
            break;
        }

        switch (tag->type) {
            case MULTIBOOT_TAG_CMDLINE:
                klog_debug("KERN", "Found cmdline tag in multiboot info");
                parse_cmdline((multiboot_tag_cmdline_t *)tag);
                break;

            case MULTIBOOT_TAG_MMAP:
                klog_debug("PMM", "Found memory map tag");
                parse_memory_map((multiboot_tag_mmap_t *)tag);
                found_memory = 1;
                break;

            case MULTIBOOT_TAG_BASIC_MEMINFO: {
                multiboot_tag_basic_meminfo_t *meminfo =
                    (multiboot_tag_basic_meminfo_t *)tag;
                klog_debug("PMM", "Found basic meminfo tag");
                klog_debug("PMM", "mem_lower=%XKB, mem_upper=%XKB",
                          meminfo->mem_lower, meminfo->mem_upper);

                /* NOTE: Do NOT add memory from basic meminfo here!
                 * The memory map (MULTIBOOT_TAG_MMAP) is more accurate and
                 * already covers all available memory. Adding memory from
                 * basic meminfo in addition to memory map causes overlapping
                 * regions, which leads to duplicate page allocations.
                 * Basic meminfo is only useful as a fallback if memory map
                 * is not available (handled at the end of parsing).
                 */
                break;
            }

            default:
                /* Ignore other tags */
                break;
        }

        /* Move to next tag (size includes padding, but we need to align) */
        tag = (multiboot_tag_t *)((uint8_t *)tag + ((tag->size + 7) & ~7));

        /* Safety check - don't read beyond total_size */
        if ((uint64_t)((uint8_t *)tag - (uint8_t *)mbi) >= total_size) {
            break;
        }
    }

use_default_cmdline:
    /* Fallback to embedded command line if multiboot didn't provide one */
    if (kernel_cmdline[0] == '\0') {
        const char *embedded = embedded_cmdline;
        size_t i = 0;

        /* Copy embedded cmdline to global buffer */
        while (i < sizeof(kernel_cmdline) - 1 && embedded[i] != '\0') {
            kernel_cmdline[i] = embedded[i];
            i++;
        }
        kernel_cmdline[i] = '\0';

        klog_debug("KERN", "Using embedded command line: '%s'", kernel_cmdline);
    }

    /* Fallback: If no memory info found, use default QEMU memory map */
    if (!found_memory) {
        klog_debug("PMM", "No memory info found, using default map for QEMU");
        /* QEMU default: 128MB starting at 0 */
        /* Kernel now starts at 4MB, add memory from 4MB to 128MB */
        pmm_add_region(0x400000, 128 * 1024 * 1024 - 0x400000);
    }

    klog_debug("PMM", "Multiboot2 parsing complete");
}

/* Get multiboot info address and size for PMM reservation */
void multiboot_get_info(uint32_t *addr, uint32_t *size) {
    if (addr != NULL) {
        *addr = stored_mbi_addr;
    }
    if (size != NULL) {
        *size = stored_mbi_size;
    }
}

/* Accessor function to get kernel command line */
const char *multiboot_get_cmdline(void) {
    klog_debug("KERN", "Parsing kernel command line...");

    if (kernel_cmdline[0] != '\0') {
        klog_debug("KERN", "Raw: '%s'", kernel_cmdline);

        /* Parse and display known keys */
        const char *quote = cmdline_get_value("quote");
        if (quote != NULL) {
            klog_debug("KERN", "quote=\"%s\"", quote);
        }

        const char *author = cmdline_get_value("author");
        if (author != NULL) {
            klog_debug("KERN", "author=%s", author);
        }

        klog_debug("KERN", "Parsing complete");
    } else {
        klog_debug("KERN", "No command line specified");
    }

    return kernel_cmdline;
}
